### ISSUE TITLE
Hey, Your discord account has been hacked. Change your passwords.

### ISSUE THREAD

**Issue by thatrex** [WonderWoman1977/Library-of-Mount-Olympus#1]

**Comment by thatrex** [comment]
@WonderWoman1977 DISCORD ACCOUNT HACKED

**Comment by WonderWoman1977** [comment]
I don’t have access to that account anymore….I cannot even change my password on it……I have already opened the issue with Discord security support.

 

Wonder Woman

**Comment by thatrex** [comment]
oof, i guess you changed your accounts email to the one the fake discord support gave :(
they tried the same thing with me using your account.

unfortunately you probably wont get your account back. but good you opened an issue. 

you will be happy to know 2 of the fake support accounts were banned while i was talking to them lol
